//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int ClienteId { get; set; }
        public int TipoDocumentoId { get; set; }
        public string NumeroDocumento { get; set; }
        public int TipoClienteId { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Empleador Empleador { get; set; }
    }
}
